services:
  mongodb:
    image: mongodb/mongodb-community-server:7.0.11-ubuntu2204
    container_name: mongodb
    ports:
      - "27017:27017"

  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scraper 
    depends_on:
      - mongodb
    ports:
      - "8080:8080"

  client:
    build:
      context: ./client/
    container_name: client
    depends_on:
      - scraper
    ports:
      - "5173:80"
